/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.memory.vista;

import com.memory.modelo.entidades.Puntuacion;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;

/**
 *
 * @author Alberto Pérez Castañeda
 */
public class GUIPuntuacion extends javax.swing.JFrame {

    /**
     * Creates new form GUIPuntuacion
     */
    public GUIPuntuacion() {
        initComponents();
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JList<Puntuacion> getlistaPuntuacion() {
        return listaPuntuacion;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JButton getBotonSalir() {
        return botonSalir;
    }

    public JButton getBotonBorrar() {
        return botonBorrar;
    }  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPuntuacion = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        botonSalir.setText("Salir");
        getContentPane().add(botonSalir);

        botonBorrar.setText("Eliminar datos");
        getContentPane().add(botonBorrar);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("PUNTUACIÓN");
        getContentPane().add(jLabel2);

        listaPuntuacion.setBackground(new java.awt.Color(153, 204, 255));
        listaPuntuacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(listaPuntuacion);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Puntuacion> listaPuntuacion;
    // End of variables declaration//GEN-END:variables
}
